import type { NextPage } from "next";
import Head from "next/head";
import {
	Hero,
	Skills,
	Projects,
	WorkExperience,
	About,
	Contact,
} from "Components";

const Home: NextPage = () => (
	<>
		<Head>
			<title>Kuangbeibei</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<Hero />
		<About />
		<Projects />
		<Skills />
		<WorkExperience />
		<Contact />
	</>
);

export default Home;
