import type { NextPage } from "next";
import Head from "next/head";
import {
	Header,
	Hero,
	Skills,
	Projects,
	WorkExperience,
	About,
	Contact,
	Footer
} from "Components";

const Home: NextPage = () => (
	<>
		<Head>
			<title>Kuangbeibei</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<Header />
		<main id="content">
			<Hero />
			<About />
			<WorkExperience />
			<Skills />
			<Projects />
			<Contact />
		</main>
		<Footer />
	</>
);

export default Home;
